# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkz2BB_K6YaiUWKFBozWbaBSEJ8iNZ6j
"""

print ("hello world")